name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Executa a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Criar Diretório de Saída
        run: mkdir -p dist

      # Gera a animação Snake
      - name: Gerar Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: Gab360riel
          outputs: dist/github-contribution-grid-snake.svg

      - name: Verificar se o Arquivo Snake foi Gerado
        run: ls -l dist

      # Publica no GitHub Pages
      - name: Publicar no GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: snake-animation
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
